FIND_PATH(SDL2_TTF_INCLUDE_DIR SDL_ttf.h
  HINTS
  $ENV{SDL2DIR}
  PATH_SUFFIXES include/SDL2 include
  PATHS ${SDL2_SEARCH_PATHS})

FIND_LIBRARY(SDL2_TTF_LIBRARY
  NAMES SDL2_ttf
  HINTS
  $ENV{SDL2DIR}
  PATH_SUFFIXES lib64 lib lib/x64 lib/x86
  PATHS ${SDL2_SEARCH_PATHS})

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS SDL2_TTF_LIBRARY SDL2_TTF_INCLUDE_DIR)
