freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script:
    - pkg install -y cmake glm mesa-libs jsoncpp sdl2
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
    - make
    - make install
