name: build

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libglm-dev libsdl2-dev libsdl2-ttf-dev libjsoncpp-dev
      - name: Configure
        run: |
          mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build
          cmake -DCMAKE_BUILD_TYPE=RELEASE $GITHUB_WORKSPACE
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/build
          make
          sudo make install
